global:
  scrape_interval: 10s
scrape_configs:
  - job_name: server
    static_configs:
      - targets: [ 'server:9091' ]
    metrics_path: '/metrics'
  - job_name: client
    static_configs:
      - targets: [ 'client:9092' ]
    metrics_path: '/metrics'